name = "goldie-inventory-watcher"
main = "src/index.js"
compatibility_date = "2026-08-19"

[triggers]
crons = ["0 * * * *"]

[vars]
ALERT_EMAIL = "goldiesoldme@gmail.com"
INVENTORY_FEED_URL = "https://fortcollins.clscars.com/wp-json/cls/v2/vehicles"

[[kv_namespaces]]
binding = "INVENTORY_KV"
id = "1733c36bce64412d97bfdb113a6ba905"
